# Generated by Django 2.0.5 on 2018-06-06 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('journal', '0002_auto_20180605_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NS', 'Not Selected')], default='NS',
                                   max_length=2),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 8, 18, 27, 14, 572727)),
        ),
        migrations.AlterField(
            model_name='journal',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='journal_cover'),
        ),
    ]
