# Generated by Django 2.0.5 on 2018-06-06 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('journal', '0003_auto_20180606_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 8, 18, 29, 33, 881494)),
        ),
    ]
