# Generated by Django 2.0.5 on 2018-06-06 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('journal', '0004_auto_20180606_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 8, 22, 30, 44, 719916)),
        ),
    ]
