# Generated by Django 2.0.5 on 2018-05-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20180527_1522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Journal',
            new_name='Article',
        ),
    ]
