# Generated by Django 2.0.5 on 2018-06-09 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('journal', '0005_auto_20180606_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='short_disc',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 11, 21, 26, 57, 849413)),
        ),
    ]
