# Generated by Django 2.0.5 on 2018-06-10 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('journal', '0006_auto_20180609_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_desc',
            field=models.CharField(default='', max_length=360),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 19, 33, 18, 471961)),
        ),
    ]
