# Generated by Django 2.0.5 on 2018-06-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('journal', '0006_auto_20180527_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
