# Generated by Django 2.0.5 on 2018-06-01 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0011_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_describe',
                 models.CharField(blank=True, help_text='Enter short Description', max_length=240, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscribers',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.UserAddition'),
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='useraddition',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraddition',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='_useraddition_subscribers_+',
                                         to='journal.UserAddition'),
        ),
    ]
