# Generated by Django 2.0.5 on 2018-06-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('journal', '0013_auto_20180601_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscribed',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_subscribed_+',
                                         to='journal.UserProfile'),
        ),
    ]
