# Generated by Django 2.0.5 on 2018-06-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('journal', '0015_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, height_field=120, upload_to='', width_field=120),
        ),
    ]
