# Generated by Django 2.0.5 on 2018-06-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('journal', '0020_auto_20180602_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/static/journal/images/default.png', upload_to='avatars'),
        ),
    ]
