# Generated by Django 2.0.5 on 2018-06-04 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('journal', '0023_auto_20180603_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 10, 56, 30, 62630)),
        ),
    ]
