# Generated by Django 2.0.5 on 2018-06-04 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('journal', '0024_emailverification_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='main_text',
        ),
        migrations.AlterField(
            model_name='article',
            name='short_desc',
            field=models.CharField(default=' ', max_length=10000),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 19, 45, 5, 750293)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
    ]
